(setq shopping-ingredients
      '("Squash" (:class "Fresh vegetables")
        "Butternut squash" (:class "Fresh vegetables")
        "Garlic cloves" (:class "Fresh vegetables" :subclass "Onion genus")
        "Salt" (:class "Condiments")
        "Black pepper" (:class "Dried spices")
        "White pepper" (:class "Dried spices")
        "Cayenne pepper" (:class "Dried spices")
        "Saffron" (:class "Dried spices")
        "Bay leaves" (:class "Dried spices")
        "Olive oil" (:class "Oils")
        "Sunflower oil" (:class "Oils")
        "Groundnut oil" (:class "Oils")
        "Walnuts" (:class "Nuts")
        "Hazelnuts" (:class "Nuts")
        "Pappardelle pasta" (:class "Pasta and noodles")
        "Wholewheat penne pasta" (:class "Pasta and noodles")
        "Unsalted butter" (:class "Dairy")
        "Sage leaves" (:class "Fresh herbs")
        "Fresh dill" (:class "Fresh herbs")
        "Parmesan cheese" (:class "Cheeses")
        "Wholegrain rice" (:class "Rice")
        "Hard tofu" (:class "Tofu")
        "Shallots" (:class "Fresh vegetables" :subclass "Onion genus")
        "Garlic" (:class "Fresh vegetables" :subclass "Onion genus")
        "Garlic head" (:class "Fresh vegetables" :subclass "Onion genus")
        "Red chilli" (:class "Fresh vegetables" :subclass "Peppers")
        "Soy sauce" (:class "Condiments")
        "Dark soy sauce" (:class "Condiments")
        "Light soy sauce" (:class "Condiments")
        "Sweet soy sauce" (:class "Condiments")
        "Cashew nuts" (:class "Nuts")
        "Pine nuts" (:class "Nuts")
        "Spring onions" (:class "Fresh vegetables" :subclass "Onion genus")
        "Pak choi" (:class "Fresh vegetables" :subclass "Greens")
        "Choi sum" (:class "Fresh vegetables" :subclass "Greens")
        "Sesame oil" (:class "Oils")
        "Jerusalem artichokes" (:class "Fresh vegetables")
        "Lemons" (:class "Fresh fruit" :subclass "Citrus")
        "Limes" (:class "Fresh fruit" :subclass "Citrus")
        "Thyme sprigs" (:class "Fresh herbs")
        "Cherry tomatoes" (:class "Fresh fruit" :subclass "Tomatoes")
        "Manouri" (:class "Cheeses")
        "White chicory" (:class "Fresh vegetables")
        "Red chicory" (:class "Fresh vegetables")
        "Basil" (:class "Fresh herbs")
        "Flat leaf parsley" (:class "Fresh herbs")
        "Rocket" (:class "Fresh vegetables" :subclass "Greens")
        "Eggs" (:class "Eggs")
        "Duck eggs" (:class "Eggs")
        "Greek yoghurt" (:class "Dairy")
        "Chilli flakes" (:class "Dried spices")
        "Chilli powder" (:class "Dried spices")
        "Sweet paprika" (:class "Dried spices")
        "Fresh ginger" (:class  "Fresh vegetables")
        "Red chillis" (:class "Fresh vegetables")
        "Green chillis" (:class "Fresh vegetables")
        "Chipotles" (:class "Canned vegetables")
        "Crème fraîche" (:class "Dairy")
        "Coriander" (:class "Fresh herbs")
        "Ground coriander" (:class "Dried spices")
        "Lemongrass stalks" (:class "Fresh herbs")
        "Sweet potatoes" (:class "Fresh vegetables")
        "Potatoes" (:class "Fresh vegetables")
        "Small potatoes" (:class "Fresh vegetables")
        "Red peppers" (:class "Fresh vegetables")
        "Yellow peppers" (:class "Fresh vegetables")
        "Large aubergines" (:class "Fresh vegetables")
        "White cabbage" (:class "Fresh vegetables")
        "Kohlrabi" (:class "Fresh vegetables")
        "Courgettes" (:class "Fresh vegetables")
        "French beans" (:class "Fresh vegetables")
        "Parsnips" (:class "Fresh vegetables")
        "Caster sugar" (:class "Condiments")
        "Muscovado sugar" (:class "Condiments")
        "Sugar" (:class "Condiments")
        "Brown sugar" (:class "Condiments")
        "Cider vinegar" (:class "Condiments" :subclass "Vinegars")
        "Balsamic vinegar" (:class "Condiments" :subclass "Vinegars")
        "Red wine vinegar" (:class "Condiments" :subclass "Vinegars")
        "Tomatoes" (:class "Fresh fruit")
        "Small tomatoes" (:class "Fresh fruit")
        "Plum tomatoes" (:class "Fresh fruit")
        "Curry leaves" (:class "Dried spices")
        "Fenugreek seeds" (:class "Dried spices")
        "Mustard seeds" (:class "Dried spices")
        "Vegetable oil" (:class "Oils")
        "Hazelnut oil" (:class "Oils")
        "Cinnamon" (:class "Dried spices")
        "Cinnamon sticks" (:class "Dried spices")
        "Allspice" (:class "Dried spices")
        "Turmeric" (:class "Dried spices")
        "Cloves" (:class "Dried spices")
        "Coriander seeds" (:class "Dried spices")
        "Cumin seeds" (:class "Dried spices")
        "Ground cumin" (:class "Dried spices")
        "Cardamom pods" (:class "Dried spices")
        "Frozen peas" (:class "Frozen vegetables")
        "Large onions" (:class "Fresh vegetables" :subclass "Onion genus")
        "Small onions" (:class "Fresh vegetables" :subclass "Onion genus")
        "Medium onions" (:class "Fresh vegetables" :subclass "Onion genus")
        "Fresh mint" (:class "Fresh herbs")
        "Parsley" (:class "Fresh herbs")
        "Thyme" (:class "Fresh herbs")
        "Rosemary" (:class "Fresh herbs")
        "Buffalo mozzarella" (:class "Cheeses")
        "Tabasco" (:class "Condiments")
        "Plain yoghurt" (:class "Dairy")
        "Avocado" (:class "Fresh vegetables")
        "Leeks" (:class "Fresh vegetables")
        "Spinach" (:class "Fresh vegetables")
        "Baby spinach" (:class "Fresh vegetables")
        "Alfalfa sprouts" (:class "Fresh vegetables")
        "Celeriac" (:class "Fresh vegetables")
        "Lemon juice" (:class "Fresh fruit")
        "Lime juice" (:class "Fresh fruit")
        "Lime zest" (:class "Fresh fruit")
        "Lemon zest" (:class "Fresh fruit")
        "Dried sour cherries" (:class "Dried fruit")
        "Cheddar cheese" (:class "Cheeses")
        "Feta cheese" (:class "Cheeses")
        "Hard goat's cheese" (:class "Cheeses")
        "Soft goat's cheese" (:class "Cheeses")
        "Black beans" (:class "Pulses")
        "Puy lentils" (:class "Pulses")
        "Split red lentils" (:class "Pulses")
        "Tortillas" (:class "Baked goods")
        "White breadcrumbs" (:class "Baked goods")
        "Sourdough bread" (:class "Baked goods")
        "Milk" (:class "Dairy")
        "Sour cream" (:class "Dairy")
        "Double cream" (:class "Dairy")
        "Powdered non-fat milk" (:class "Dairy")
        "Baking powder" (:class "Baking ingredients")
        "Self-raising flour" (:class "Baking ingredients")
        "Cornflour" (:class "Baking ingredients")
        "Plain flour" (:class "Baking ingredients")
        "Puff pastry" (:class "Baking ingredients")
        "Vanilla extract" (:class "Baking ingredients")
        "Yeast" (:class "Baking ingredients")
        "Tomato purée" (:class "Condiments")
        "White wine" (:class "Alcohol")
        "Vegetable stock" (:class "Timesaving ingredients")
        "Quinoa" (:class "Grains")
        "Freekeh" (:class "Grains")
        "Bulghar wheat" (:class "Grains")
        "Peanuts" (:class "Nuts")
        "Almonds" (:class "Nuts")
        "Peanut butter" (:class "Condiments")
        "French wholegrain mustard" (:class "Condiments")
        "Tinned pineapple chunks" (:class "Tinned fruit")
        "Kale" (:class "Fresh vegetables")
        "Cucumber" (:class "Fresh vegetables")
        "Cauliflower" (:class "Fresh vegetables")
        "Fenugreek" (:class "Dried spices")
        "Capers" (:class "Preserved vegetables")
        "Young goat's cheese" (:class "Cheeses")
        "Goat's curd" (:class "Cheeses")
        "Fennel bulbs" (:class "Fresh vegetables")
        "Fennel seeds" (:class "Dried spices")
        "Asian crisp-fried shallots" (:class "Condiments")
        "Fresh egg noodles" (:class "Pasta and noodles")
        "Sambal olek" (:class "Condiments")
        "Beansprouts" (:class "Fresh vegetables")
        "Iceberg lettuce" (:class "Fresh vegetables")
        "Radishes" (:class "Fresh vegetables")
        "Breadcrumbs" (:class "Baked goods")
        "Stale bread" (:class "Baked goods")
        "Fresh broad beans" (:class "Fresh vegetables")
        "Frozen broad beans" (:class "Frozen vegetables")
        "Pomegranate molasses" (:class "Condiments")
        "Tahini" (:class "Condiments")
        ))
