(defun uk-tablespoons-to-ml (n-tablespoons)
  (* n-tablespoons 17.758))

(defun us-tablespoons-to-ml (n-tablespoons)
  (* n-tablespoons 14.787))

(defun uk-teaspoons-to-ml (n-teaspoons)
  (* n-teaspoons 3.552))

(defun metric-tablespoons-to-ml (n-tablespoons)
  (* n-tablespoons 15))

(setq shopping-recipes
 `((:title "Pappardelle with squash and sage"
    :ingredients (("Squash" 750 g)
                  ("Garlic cloves" 5)
                  ("Salt")
                  ("Black pepper")
                  ("Olive oil" ,(uk-tablespoons-to-ml 4) ml)
                  ("Walnuts" 75 g)
                  ("Pappardelle pasta" 250 g)
                  ("Unsalted butter" 50 g)
                  ("Sage leaves" 15)
                  ("Parmesan cheese")))
   (:title "Tofu stir-fry"
    :ingredients (("Wholegrain rice")
                  ("Hard tofu")
                  ("Shallots")
                  ("Garlic")
                  ("Red chillis")
                  ("Fresh ginger")
                  ("Soy sauce")
                  ("Cashew nuts")
                  ("Spring onions")))
   (:title "Vegetarian fried rice"
    :ingredients (("Wholegrain rice")
                  ("Large onions" 1)
                  ("Spring onions" 4)
                  ("Frozen peas")
                  ("Eggs" 4)
                  ("Soy sauce")))
   (:title "Pasta with tomatoes and mozzarella"
    :ingredients (("Wholewheat penne pasta")
                  ("Cherry tomatoes")
                  ("Basil")
                  ("Parmesan cheese")
                  ("Buffalo mozzarella")
                  ("Black pepper")
                  ("Olive oil")))
   (:title "Vegetarian burritos"
    :ingredients (("Tortillas")
                  ("Black beans")
                  ("Ground cumin")
                  ("Cheddar cheese")
                  ("Cherry tomatoes")
                  ("Large onions" 1)
                  ("Coriander")
                  ("Avocado")
                  ("Plain yoghurt")
                  ("Limes" 2)
                  ("Tabasco")
                  ("Chilli flakes"))
   :notes "1 lime for the salsa: tomatoes, onion, lime juice, salt, tabasco, coriander. Other lime for guacamole: avocado, lime juice, salt, pepper, chilli flakes")
))
